import json

with open('src/data/games.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

updates = {
    "geometry-game-3d": {
        "longDescription": "Geometry Game 3D pushes the boundaries of the rhythm platformer genre by implementing true three-dimensional gameplay where you navigate through fully realized 3D environments with depth, height, and width all playing crucial roles in obstacle avoidance. When you play Geometry Game 3D online free, you'll experience a radical evolution of the formula that goes beyond simple visual enhancements to fundamentally change how you interact with the game world through camera controls, spatial navigation, and obstacles that exist in genuine 3D space rather than layered 2D planes. The game features dynamic camera systems that rotate around your character, providing multiple perspectives on the same challenges and requiring you to develop true spatial awareness as obstacles approach from angles impossible in traditional 2D gameplay. What sets Geometry Game 3D apart from other 3D variants is its commitment to full three-dimensional mechanics—you're not just seeing 3D graphics but actually navigating through 3D space where obstacles can be above, below, beside, or behind you, demanding constant spatial orientation and depth perception. Players appreciate how the game maintains rhythm synchronization while adding the complexity of 3D navigation, as the soundtrack still guides your timing but now you must also consider positioning in three-dimensional space. The visual design uses sophisticated lighting, shadows, and perspective effects to help you judge distances and positions, with color-coded depth indicators and particle trails that make spatial relationships clear even during fast-paced sequences. The difficulty curve introduces 3D mechanics gradually, starting with simple depth-based challenges and building to complex sequences where you must navigate through rotating 3D structures, spiral around cylindrical obstacles, and time jumps while the camera perspective shifts dynamically. What makes this variant special is how it appeals to players seeking genuinely new gameplay experiences rather than just visual upgrades—the 3D mechanics create puzzle-solving elements as you must figure out optimal paths through three-dimensional obstacle arrangements. The game includes multiple camera modes that let you choose perspectives based on preference, from third-person views that show your character in context to first-person modes that create intense immersion. With its true 3D gameplay mechanics, sophisticated spatial challenges, dynamic camera systems, and the innovative blend of rhythm-based timing with three-dimensional navigation, Geometry Game 3D represents a bold evolution that proves the formula can successfully expand into new dimensions while maintaining its core appeal.",
        "faq": [
            {"q": "Is Geometry Game 3D free to play online?", "a": "Yes, you can play Geometry Game 3D online free without downloads or payments. The game provides full access to its three-dimensional levels, camera systems, and spatial navigation mechanics. No registration is required—simply load the game and experience true 3D rhythm platforming immediately."},
            {"q": "How does true 3D gameplay differ from regular Geometry Dash?", "a": "Geometry Game 3D features genuine three-dimensional navigation where obstacles exist in full 3D space rather than layered 2D planes. You must consider depth, height, and width simultaneously, with dynamic cameras that rotate to show different perspectives. This creates spatial challenges impossible in 2D, requiring true depth perception and orientation awareness."},
            {"q": "Do I need special controls for 3D navigation?", "a": "The core one-button jump control remains, but 3D navigation adds complexity through spatial positioning and camera awareness. You must judge distances in three dimensions and time jumps while considering your position in 3D space. Some versions include camera control options, but the fundamental simplicity of one-button gameplay is preserved."},
            {"q": "What strategies help with 3D spatial challenges?", "a": "Use shadows and lighting to judge depth and distance accurately. Pay attention to how objects scale as they approach—larger means closer. Practice with static camera angles before trying dynamic rotation modes. Build spatial memory by replaying sections to understand 3D obstacle arrangements. Take time to orient yourself after camera perspective shifts."},
            {"q": "Is Geometry Game 3D harder than traditional versions?", "a": "It presents different challenges rather than being strictly harder. The 3D spatial navigation requires skills beyond timing—depth perception, spatial reasoning, and orientation awareness. Some players find 3D easier because they can see obstacles from multiple angles, while others need time to adapt to thinking in three dimensions. Difficulty depends on your spatial reasoning abilities."}
        ],
        "tips": [
            "Use shadows and lighting effects to accurately judge obstacle depth and distance",
            "Practice with fixed camera angles before attempting dynamic rotation modes",
            "Pay attention to object scaling—larger objects are closer in 3D space",
            "Build spatial memory by replaying sections to understand 3D arrangements",
            "Take time to reorient yourself after camera perspective shifts",
            "Use peripheral vision to track obstacles approaching from different spatial angles",
            "Experiment with different camera modes to find perspectives that work for you",
            "Focus on one spatial dimension at a time when overwhelmed by 3D complexity",
            "Notice how particle trails help visualize your movement path through 3D space",
            "Take breaks to prevent spatial disorientation during extended play sessions"
        ]
    },
    
    "geometry-world": {
        "longDescription": "Geometry Dash World is an official spin-off that serves as a perfect introduction to the series by offering ten carefully selected levels across five distinct themed worlds, each showcasing different aspects of the game's mechanics and visual styles. When you play Geometry World online free, you'll experience a curated journey through diverse environments from fiery volcanic landscapes to serene aquatic zones, with each world featuring two levels that demonstrate unique obstacle patterns and aesthetic approaches. The game functions as both a standalone experience for newcomers and a content expansion for veterans, offering exclusive levels not found in other versions while maintaining the core gameplay that made the series popular. What makes Geometry World special is its world-based structure that creates a sense of progression and variety—instead of a linear level list, you unlock themed worlds that each tell a visual story through their design language and obstacle themes. Players appreciate how the ten levels span a wide difficulty range from beginner-friendly tutorials to challenging stages that test advanced skills, making the game accessible to new players while offering enough difficulty to engage experienced ones. Each world features distinct visual themes with cohesive color palettes, environmental details, and obstacle designs that create memorable identities—the fire world uses reds and oranges with lava-themed hazards, while the ice world employs blues and whites with crystalline structures. The level design showcases the evolution of Geometry Dash's mechanics, with each stage introducing or emphasizing different game modes from cube jumping to ship flying, wave navigation to ball rolling. What sets Geometry World apart from other spin-offs is its role as a gateway experience—it provides enough content to understand what makes the series special without overwhelming newcomers with the full game's complexity or custom level ecosystem. The soundtrack features energetic electronic music that matches each world's theme, creating audio-visual synchronization that makes successful runs feel satisfying and rhythmic. With its world-based progression, diverse themed environments, ten carefully crafted levels spanning multiple difficulties, and the perfect balance of accessibility and challenge, Geometry Dash World stands as an ideal entry point that captures the series' essence in a focused, polished package.",
        "faq": [
            {"q": "Is Geometry Dash World free to play online?", "a": "Yes, you can play Geometry Dash World online free without downloads or payments. The game provides full access to all five themed worlds and ten exclusive levels. No registration is required—simply start playing and experience the world-based progression and diverse environments immediately."},
            {"q": "How many levels are in Geometry Dash World?", "a": "Geometry World features ten exclusive levels organized into five themed worlds, with two levels per world. Each world has distinct visual themes and obstacle patterns, ranging from fire and ice to mechanical and aquatic environments. The levels span beginner to advanced difficulties, providing a complete progression experience."},
            {"q": "How does Geometry World differ from other Geometry Dash games?", "a": "Geometry World uses a world-based structure instead of a linear level list, with five themed environments that each contain two levels. It serves as a curated introduction to the series with exclusive content not found in other versions. The game lacks the level editor but offers a focused experience perfect for newcomers and veterans seeking fresh official content."},
            {"q": "What difficulty level should I expect in Geometry World?", "a": "The ten levels span from easy to hard difficulty, creating a natural progression curve. Early worlds feature beginner-friendly levels that teach mechanics, while later worlds present challenging stages that test advanced skills. This range makes Geometry World accessible to newcomers while providing enough difficulty to engage experienced players."},
            {"q": "Can I unlock all worlds immediately or must I progress?", "a": "Geometry World typically uses a progression system where you unlock new worlds by completing previous ones, creating a structured journey through the themed environments. This progression ensures you build skills gradually and experience the difficulty curve as intended. Some versions may allow world selection, but the designed progression provides the best experience."}
        ],
        "tips": [
            "Complete worlds in order to experience the intended difficulty progression",
            "Pay attention to each world's visual theme for obstacle timing cues",
            "Use practice mode to learn new mechanics introduced in each world",
            "Notice how each world emphasizes different game modes and skills",
            "Listen to soundtrack changes that signal transitions between world themes",
            "Master earlier worlds before tackling later ones with higher difficulty",
            "Appreciate the visual storytelling in each world's environmental design",
            "Focus on completing levels before attempting secret coin collection",
            "Take breaks between worlds to maintain focus and prevent fatigue",
            "Celebrate unlocking new worlds—each represents progress in your skill development"
        ]
    },
    
    "geometry-meltdown": {
        "longDescription": "Geometry Dash Meltdown is an official spin-off that delivers an intense, high-energy experience through three exclusive levels featuring some of the most aggressive soundtracks and visually striking designs in the Geometry Dash franchise. When you play Geometry Meltdown online free, you'll encounter The Seven Seas, Viking Arena, and Airborne Robots—three levels that showcase a darker, more intense aesthetic with fiery color schemes, industrial themes, and obstacle patterns that demand quick reflexes and sustained concentration. What makes Meltdown special is its focus on creating an adrenaline-pumping atmosphere where every element from the pounding electronic music to the explosive visual effects works together to create a sense of urgency and intensity. The game features soundtracks by F-777 that are among the most energetic in the series, with aggressive beats and intense drops that drive the rhythm-based gameplay while matching the levels' fierce visual presentation. Players appreciate how Meltdown maintains accessibility despite its intense atmosphere—the three levels range from easy to hard difficulty, making the game approachable for intermediate players while still offering challenge through demanding obstacle sequences and tight timing windows. Each level includes three secret coins hidden in challenging locations that reward skilled players with extra objectives beyond simple completion. The visual design uses bold reds, oranges, and industrial grays to create a cohesive aesthetic that feels more aggressive and mature than the series' typically colorful presentation. What sets Meltdown apart from other spin-offs is its commitment to intensity—every aspect is designed to create an exciting, high-stakes feeling that makes successful runs feel like epic victories. The obstacle patterns feature creative arrangements that feel fresh rather than recycled, with each level introducing unique challenges from ship sequences through narrow industrial corridors to wave sections that demand precise control through chaotic environments. The three-level structure provides a complete experience that can be finished in a single session while offering enough replayability through secret coins and score optimization to keep players engaged long-term. With its intense atmosphere, aggressive soundtracks, bold visual design, and the perfect balance of accessibility and challenge, Geometry Dash Meltdown stands as one of the most exciting spin-offs that captures the series' core appeal while delivering a distinctly fiercer experience.",
        "faq": [
            {"q": "Is Geometry Dash Meltdown free to play online?", "a": "Yes, you can play Geometry Dash Meltdown online free without downloads or payments. The game provides full access to all three intense levels—The Seven Seas, Viking Arena, and Airborne Robots—along with their secret coins and challenges. No registration is required to experience this high-energy spin-off immediately."},
            {"q": "How many levels are in Geometry Dash Meltdown?", "a": "Meltdown features three exclusive levels with difficulties ranging from easy to hard. While fewer than some versions, each level is designed with intense soundtracks by F-777 and aggressive visual themes. The focus on quality and intensity makes each level feel like a complete experience that showcases the series' high-energy potential."},
            {"q": "How does Meltdown differ from other Geometry Dash games?", "a": "Meltdown emphasizes intensity and aggression with darker visual themes, industrial aesthetics, and some of the most energetic soundtracks in the series. It lacks the level editor but offers three curated levels designed for adrenaline-pumping gameplay. The atmosphere is fiercer and more mature than typical Geometry Dash presentations while maintaining core mechanics."},
            {"q": "What difficulty level should I expect in Meltdown?", "a": "The three levels range from easy to hard difficulty, making Meltdown accessible to intermediate players who've mastered basic mechanics. The Seven Seas serves as an approachable entry point, Viking Arena increases challenge, and Airborne Robots delivers hard-difficulty sequences. The progression provides a complete skill curve within three levels."},
            {"q": "Can I find all three secret coins in each Meltdown level?", "a": "Yes, each of the three levels contains three secret coins hidden in challenging locations. Finding them requires skill and exploration, often demanding specific routes or precise execution. Practice mode helps locate coins safely, and collecting all nine coins across the three levels provides extra objectives for players seeking complete mastery."}
        ],
        "tips": [
            "Let the aggressive soundtracks guide your timing through intense sequences",
            "Use practice mode to memorize obstacle patterns before attempting full runs",
            "Stay calm despite the intense atmosphere—panic leads to mistakes",
            "Focus on smooth, controlled movements rather than frantic reactions",
            "Watch for visual cues in the industrial themes that signal obstacle timing",
            "Master ship sections separately as they feature prominently in Meltdown",
            "Study secret coin locations in practice mode before collection attempts",
            "Take breaks between runs to maintain focus during intense sequences",
            "Appreciate the bold visual design but don't let it distract from obstacles",
            "Celebrate completing all three levels—it demonstrates solid intermediate skill"
        ]
    }
}

for game in data['games']:
    if game['id'] in updates:
        game['longDescription'] = updates[game['id']]['longDescription']
        game['faq'] = updates[game['id']]['faq']
        game['tips'] = updates[game['id']]['tips']
        print(f"Updated: {game['id']}")

with open('src/data/games.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Batch 10 complete - All 20 games updated!")
